blueprint:
  name: Pico Remote
  description: "Control lights with 5 button Pico remote"
  domain: automation
  input:
    pico_remote:
      name: Pico Remote
      description: 'Select the pico remote to configure:'
      selector:
        device:
          filter:
            - integration: lutron_caseta
              model: PJ2-3BRL-GXX-X01
    light_target:
      name: Light
      selector:
        target:
          entity:
            domain: light
trigger:
- platform: device
  device_id: !input 'pico_remote'
  domain: lutron_caseta
  type: press
  subtype: 'on'
  id: 'on'
- platform: device
  device_id: !input 'pico_remote'
  domain: lutron_caseta
  type: press
  subtype: 'raise'
  id: 'raise'
- platform: device
  device_id: !input 'pico_remote'
  domain: lutron_caseta
  type: press
  subtype: 'stop'
  id: 'stop'
- platform: device
  device_id: !input 'pico_remote'
  domain: lutron_caseta
  type: press
  subtype: 'lower'
  id: 'lower'
- platform: device
  device_id: !input 'pico_remote'
  domain: lutron_caseta
  type: press
  subtype: 'off'
  id: 'off'
condition: []
action:
- choose:
  - conditions:
    - condition: trigger
      id: 'on'
    sequence:
    - service: light.turn_on
      target: !input 'light_target'
      data:
        brightness_pct: 100
  - conditions:
    - condition: trigger
      id: 'raise'
    sequence:
    - service: light.turn_on
      target: !input 'light_target'
      data:
        brightness_step_pct: 20
  - conditions:
    - condition: trigger
      id: 'stop'
    sequence:
    - service: light.toggle
      target: !input 'light_target'
  - conditions:
    - condition: trigger
      id: 'lower'
    sequence:
    - service: light.turn_on
      target: !input 'light_target'
      data:
        brightness_step_pct: -20
  - conditions:
    - condition: trigger
      id: 'off'
    sequence:
    - service: light.turn_off
      target: !input 'light_target'
  default: []
mode: restart
