blueprint:
  name: Pico Remote
  description: Create actions for the Pico remote
  domain: automation
  input:
    remote:
      name: Pico Remote
      description: The Pico Remote that you will be assigning actions to
      selector:
        entity:
          domain: sensor
          integration: lutron_caseta
    button_top:
      name: Top Button
      description: The top (light on) button on the Pico Remote
      default: []
      selector:
        action: {}
    button_up:
      name: Up Arrow Button
      description: The arrow up (increase brightness) button on the Pico Remote
      default: []
      selector:
        action: {}
    button_middle:
      name: Middle Button
      description: The middle (favorite) button on the Pico Remote
      default: []
      selector:
        action: {}
    button_down:
      name: Down Arrow Button
      description: The arrow down (decrease brightness) button on the Pico Remote
      default: []
      selector:
        action: {}
    button_bottom:
      name: Bottom Button
      description: The bottom (light off) button on the Pico Remote
      default: []
      selector:
        action: {}
trigger:
  - platform: state
    entity_id: !input remote
condition: []
action:
  - choose:
      - conditions:
          - condition: state
            entity_id: !input remote
            state: "1"
        sequence: !input button_top
      - conditions:
          - condition: state
            entity_id: !input remote
            state: "8"
        sequence: !input button_up
      - conditions:
          - condition: state
            entity_id: !input remote
            state: "2"
        sequence: !input button_middle
      - conditions:
          - condition: state
            entity_id: !input remote
            state: "16"
        sequence: !input button_down
      - conditions:
          - condition: state
            entity_id: !input remote
            state: "4"
        sequence: !input button_bottom
    default: []
mode: restart
